name: Common Test

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  linux:
    name: Test on OTP ${{ matrix.combo.otp-version }} and ${{ matrix.combo.os }}
    runs-on: ${{ matrix.combo.os }}

    strategy:
      fail-fast: false
      matrix:
        combo:
          - os: 'ubuntu-latest'
            otp-version: '25'
            rebar3-version: '3.16'
          - os: 'ubuntu-latest'
            otp-version: '26'
            rebar3-version: '3.22.1'
          - os: 'ubuntu-latest'
            otp-version: '27'
            rebar3-version: '3.24.0'

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.combo.otp-version }}
        rebar3-version: ${{ matrix.combo.rebar3-version }}
    - name: Update
      run: rebar3 update
    - name: Compile
      run: rebar3 compile
    - name: Dialyzer
      run: rebar3 dialyzer

