---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        otp_vsn: ['24', '23.0', '22.3']
        os: [ubuntu-latest]
        rebar3_vsn: ['3.16']
        include:
          - otp_vsn: '21.3'
            os: 'ubuntu-latest'
            rebar3_vsn: '3.15'
          - otp_vsn: '20.3'
            os: 'ubuntu-latest'
            rebar3_vsn: '3.15'
          - otp_vsn: '19.3'
            os: 'ubuntu-18.04'
            rebar3_vsn: '3.15'
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          otp-version: ${{matrix.otp_vsn}}
          rebar3-version: ${{matrix.rebar3_vsn}}
      - name: restore _build
        uses: actions/cache@v2
        with:
          path: _build
          key: _build-cache-for-os-${{runner.os}}-otp-${{steps.setup-beam.outputs.otp-version}}-rebar3-${{steps.setup-beam.outputs.rebar3-version}}-hash-${{hashFiles('rebar.lock')}}
      - name: restore rebar3's cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/rebar3
          key: rebar3-cache-for-os-${{runner.os}}-otp-${{steps.setup-beam.outputs.otp-version}}-rebar3-${{steps.setup-beam.outputs.rebar3-version}}-hash-${{hashFiles('rebar.lock')}}
      - run: rebar3 dialyzer
